### PR TITLE
Allows canceling a subscription with all supported attributes

### LINKED ISSUE #160: Allow canceling a subscription with all supported attributes
API reference
https://reference.chargify.com/v1/subscriptions-cancellations#cancel-subscription-2

Cancel Subscription allows canceling with:
 - `cancellation_message`
 - `cancellation_method`
 - `reason_code`

Currently anything passed to the `cancel` method is saved as `cancellation_message`
i.e. 
calling:
```
subscription.cancel(reason_code: "A reason")
```
results in 
```
> subscription.cancellation_message
=> '{"reason_code"=>"A reason"}'
```

### PR DESCRIPTION
**Pull request by blakeprudhomme**
Supported Attributes:
 - `cancellation_message`
 - ~`cancellation_method`~
 - `reason_code`

API reference
https://reference.chargify.com/v1/subscriptions-cancellations#cancel-subscription-2

Closes #160

### CODE REVIEW

**Comment by wsmoak** [comment]
Thanks!  We're actually checking on whether `cancellation_method` was meant to be exposed as an input attribute, so once we get that sorted out we can take a look at this.

**Comment by blakeprudhomme** [comment]
Ok that makes sense. It's not really needed for us, I just added it while I was making the update since API exposed it.

I noticed that API says: `cancellation_method : null or string`

but have seen `"cancellation_method"=>0,` returned with the subscription object

**Comment by wsmoak** [comment]
Sorry for the delay on this and the misleading docs!  We've updated them to remove the `cancellation_method` as an input attribute
https://reference.chargify.com/v1/subscriptions-cancellations/cancel-subscription

It's present in the output, but it isn't something you can set.

If you'd like to update this to remove the use of `cancellation_method` in the input, we can review it, or if you don't want to spend more time time on it we can just go ahead and add this separately. 

Thanks again for your work on it!

**Comment by YesThatAllen** [comment]
And for those who need to be able to set the method, so we can make use of your new [churn metrics](https://www.chargify.com/blog/understanding-saas-churn-metrics/)? 🙏

**Comment by blakeprudhomme** [comment]
@wsmoak `cancellation_method` removed. 👍

**Pull request merged**
