### PR TITLE
Expose access to Reason Codes

### PR DESCRIPTION
**Pull request by blakeprudhomme**
Simply allows access to fetch the list of reason codes

### CODE REVIEW

**Comment by blakeprudhomme** [comment]
Any feed back on this?

**Comment by wsmoak** [comment]
Sorry for the delay!  Can you add something under the `/examples` directory to show how you're using it?

(I'm not going to ask for tests because they are being uncooperative at the moment and we need to document how to run the local vs. remote tests.)

**Comment by blakeprudhomme** [comment]
Sure can! thanks.

**Comment by blakeprudhomme** [comment]
>tests because they are being uncooperative at the moment

@wsmoak Example added. I assume CI failing is related to the above comment?

**Comment by blakeprudhomme** [comment]
Does anything else need to been done here?

**Pull request merged**
